name: Canyon-UHC
version: 0.1.0
main: canyonuhc.UHCPlugin
commands:
  reset-uhc:
    description: Resets the UHC, killing all players
    usage: /reset-uhc
  start-uhc:
    description: Starts the UHC
    usage: /start-uhc [team-game]
  worldborder:
    description: Sets or gets the world border
    usage: /worldborder [distance] [ticks]
  glow:
    description: Glows a player
    usage: /glow [player] [color] [for-player]
  spectator:
    description: Puts you in spectator mode
    usage: /spectator
  display-name:
    description: Puts you in spectator mode
    usage: /display-name [name]
