name: maven
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/gh-pages'
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Canyon
        uses: actions/checkout@v2
        with:
          repository: canyonmodded/canyon
          submodules: recursive
          path: canyon
      - name: Setup github.ref
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
      - name: Install Canyon
        run: |
          cd canyon
          chmod +x canyon
          ./canyon p
          mvn clean install
          cd ..
      - name: Set up JDK 8
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 8
          distribution: zulu
      - name: Build with Maven
        run: mvn clean install
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: canyon-uhc-jar-artifact
          path: target/canyon-uhc-*.jar
